# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['ipa_installer.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'pymobiledevice3',
        'pymobiledevice3.lockdown',
        'pymobiledevice3.usbmux',
        'pymobiledevice3.service_connection',
        'pymobiledevice3.services',
        'pymobiledevice3.services.installation_proxy',
        'pymobiledevice3.services.afc',
        'pymobiledevice3.services.mobile_image_mounter',
        'pymobiledevice3.services.diagnostics',
        'pymobiledevice3.services.springboard',
        'pymobiledevice3.exceptions',
        'pymobiledevice3.tunneld',
        'pymobiledevice3.remote',
        'pymobiledevice3.restore',
        'construct',
        'construct.core',
        'ifaddr',
        'IPython',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'numpy',
        'pandas',
        'PIL',
        'cv2',
        'scipy',
        'notebook',
        'jupyter',
        'ipykernel',
    ],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='IPAInstaller',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
